spring:
  application:
    name: football_project
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    url: jdbc:mysql://localhost:3306/${DB_URL}
server:
  error:
    include-message: always
