spring:
  application:
    name: gigsync
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  error:
    include-message: always
  tomcat:
    max-http-post-size: 500MB

jwt:
  expiration_time: ${JWT_EXP}
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}
    s3:
      bucketName: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: 'false'