name: Deploy to EC2

on:
  push:
    branches:
      - develop
      - CICD

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-Arch Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE_TAG_NAME }}:latest \
            --push .

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval "$(ssh-agent -s)"
          ssh-add private_key.pem

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: SSH into EC2 and deploy
        env:
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          JWT_ACCESS_EXP: ${{ secrets.JWT_ACCESS_EXP }}
          JWT_REFRESH_EXP: ${{ secrets.JWT_REFRESH_EXP }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_AUTH: ${{ secrets.MONGO_AUTH }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          AWS_ACCESS: ${{ secrets.AWS_ACCESS }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_REGION: ${{ secrets.S3_REGION }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_IMAGE_TAG_NAME: ${{ vars.DOCKERHUB_IMAGE_TAG_NAME }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
            cd /home/ubuntu
          
            echo "MONGO_DATABASE=${MONGO_DATABASE}" > .env
            echo "MONGO_USERNAME=${MONGO_USERNAME}" >> .env
            echo "MONGO_PASSWORD=${MONGO_PASSWORD}" >> .env
            echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
            echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> .env
            echo "MYSQL_USER=${MYSQL_USER}" >> .env
            echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> .env
            echo "DB_URL=${DB_URL}" >> .env
            echo "DB_USER=${DB_USER}" >> .env
            echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
            echo "REDIS_HOST=${REDIS_HOST}" >> .env
            echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env
            echo "JWT_ACCESS_EXP=${JWT_ACCESS_EXP}" >> .env
            echo "JWT_REFRESH_EXP=${JWT_REFRESH_EXP}" >> .env
            echo "JWT_SECRET=${JWT_SECRET}" >> .env
            echo "MONGO_AUTH=${MONGO_AUTH}" >> .env
            echo "MONGO_HOST=${MONGO_HOST}" >> .env
            echo "AWS_ACCESS=${AWS_ACCESS}" >> .env
            echo "AWS_SECRET=${AWS_SECRET}" >> .env
            echo "S3_BUCKET=${S3_BUCKET}" >> .env
            echo "S3_REGION=${S3_REGION}" >> .env
            echo "DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}" >> .env
            echo "DOCKERHUB_IMAGE_TAG_NAME=${DOCKERHUB_IMAGE_TAG_NAME}" >> .env

            echo "환경 변수 확인:"
            cat .env | grep DOCKERHUB
            cat docker-compose.yml

            docker compose down
            docker system prune -af --volumes
            docker compose pull
            docker compose up -d --build  
          EOF