name: Deploy to EC2

on:
  push:
    branches:
      - develop
      - CICD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval "$(ssh-agent -s)"
          ssh-add private_key.pem

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu

            cat > .env <<EOT
MONGO_DATABASE=${MONGO_DATABASE}
MONGO_USERNAME=${MONGO_USERNAME}
MONGO_PASSWORD=${MONGO_PASSWORD}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=${MYSQL_DATABASE}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
DB_URL=${DB_URL}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
REDIS_HOST=${REDIS_HOST}
REDIS_PASSWORD=${REDIS_PASSWORD}
JWT_ACCESS_EXP=${JWT_ACCESS_EXP}
JWT_REFRESH_EXP=${JWT_REFRESH_EXP}
JWT_SECRET=${JWT_SECRET}
MONGO_AUTH=${MONGO_AUTH}
MONGO_HOST=${MONGO_HOST}
AWS_ACCESS=${AWS_ACCESS}
AWS_SECRET=${AWS_SECRET}
S3_BUCKET=${S3_BUCKET}
S3_REGION=${S3_REGION}
DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
DOCKERHUB_IMAGE_TAG_NAME=${DOCKERHUB_IMAGE_TAG_NAME}
EOT

            docker compose down
            docker compose pull
            docker compose up -d --build
          EOF
        env:
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          JWT_ACCESS_EXP: ${{ secrets.JWT_ACCESS_EXP }}
          JWT_REFRESH_EXP: ${{ secrets.JWT_REFRESH_EXP }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_AUTH: ${{ secrets.MONGO_AUTH }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          AWS_ACCESS: ${{ secrets.AWS_ACCESS }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_REGION: ${{ secrets.S3_REGION }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_IMAGE_TAG_NAME: ${{ secrets.DOCKERHUB_IMAGE_TAG_NAME }}